select
T1.RESOURCE_NAME RESOURCE_NAME
,T1.AGENT_LAST_NAME as AGENT_LAST_NAME
,T1.AGENT_FIRST_NAME as AGENT_FIRST_NAME
,T1."Date" AS "Date"
,T1."Hours" as "Hours"
,count(distinct T1.I_ID) as "# Accepted"
,count(distinct case when T1.N_Outb_Repl>0 then T1.I_ID END) AS "# Replied"
,count(distinct case when T1.N_obr>0 then T1.I_ID END) as "# Done"
,COUNT(DISTINCT CASE WHEN T1.N_Initiated > 0 THEN T1.I_ID END) AS "# Initiated"
,sum(T1.[RINGING DURATION]) AS "Ringing Time"
,sum(T1.[TALK DURATION]) AS "Talking Time"
,sum(T1.HOLD_DURATION ) as HOLD_DURATION
,sum(T1.AFTER_CALL_WORK_DURATION ) as AFTER_CALL_WORK_DURATION
,sum(T1.TALK_COUNT ) as TALK_COUNT
,sum(T1."AHT_voice")
, SUM(T1.[Busy Duration])


FROM

(select
R2.RESOURCE_NAME as RESOURCE_NAME
,R2.AGENT_LAST_NAME as AGENT_LAST_NAME
,R2.AGENT_FIRST_NAME as AGENT_FIRST_NAME
,DT.LABEL_YYYY_MM_DD as "Date"
,cast(DATEADD(hour,2,DT.CAL_DATE) AS time(0)) AS "Hours"
,IRF.INTERACTION_ID as I_ID
,count(distinct case when IT.INTERACTION_TYPE='Inbound' then IRF.INTERACTION_ID end) as N_Inb
,count(distinct case when IT.INTERACTION_TYPE='Outbound' then IRF.INTERACTION_ID end) as N_Outb
,count(distinct case when IT.INTERACTION_SUBTYPE='OutboundReply' and TD2.TECHNICAL_RESULT='Completed' then IRF.INTERACTION_ID end) as N_Outb_Repl
,count(distinct case when IT.INTERACTION_SUBTYPE='OutboundNew' then IRF.INTERACTION_ID end) as N_Outb_New
,count(distinct case when TD2.TECHNICAL_RESULT in ('Completed','Transferred') then IRF.INTERACTION_ID end) as N_obr
,COUNT(DISTINCT CASE WHEN IRF.HANDLE_COUNT <> 0 AND IT.INTERACTION_SUBTYPE_CODE = 'OUTBOUNDNEW' then IRF.INTERACTION_ID end) AS N_Initiated
,'' AS [Busy Duration] -- busy duration
,IRF.RING_DURATION AS [RINGING DURATION], IRF.TALK_DURATION AS [TALK DURATION]
,IRF.HOLD_DURATION 
,IRF.AFTER_CALL_WORK_DURATION 
,IRF.TALK_COUNT
,case when (IRF.TALK_COUNT)>0 then round(sum(IRF.TALK_DURATION)+sum(IRF.HOLD_DURATION)+sum(IRF.AFTER_CALL_WORK_DURATION)/sum(IRF.TALK_COUNT),2) else 0 end as "AHT_voice"

from
INFOMART.dbo.MEDIATION_SEGMENT_FACT MSF
inner join INFOMART.dbo.INTERACTION_RESOURCE_FACT IRF on MSF.INTERACTION_ID=IRF.INTERACTION_ID
inner join INFOMART.dbo.TECHNICAL_DESCRIPTOR TD2 on IRF.TECHNICAL_DESCRIPTOR_KEY=TD2.TECHNICAL_DESCRIPTOR_KEY
inner join INFOMART.dbo.RESOURCE_ R2 on IRF.RESOURCE_KEY=R2.RESOURCE_KEY
inner join INFOMART.dbo.DATE_TIME DT on IRF.END_DATE_TIME_KEY=DT.DATE_TIME_KEY
inner JOIN INFOMART.dbo.DATE_TIME DT2 ON IRF.START_DATE_TIME_KEY = DT2.DATE_TIME_KEY
inner join INFOMART.dbo.MEDIA_TYPE M on IRF.MEDIA_TYPE_KEY=M.MEDIA_TYPE_KEY
inner join INFOMART.dbo.INTERACTION_TYPE IT on IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
inner join INFOMART.dbo.IRF_USER_DATA_KEYS UK on IRF.INTERACTION_RESOURCE_ID=UK.INTERACTION_RESOURCE_ID

INNER JOIN SM_RES_STATE_FACT SRSTF ON SRSTF.RESOURCE_KEY = R2.RESOURCE_KEY
INNER JOIN RESOURCE_STATE RS ON SRSTF.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY

WHERE 
DT.LABEL_YYYY_MM_DD = '2020-01-03'
and 
M.MEDIA_NAME='Email'
and R2.RESOURCE_TYPE='Agent'
AND NOT R2.RESOURCE_NAME IN ('aionov','daniel', 'aamelin')
AND R2.RESOURCE_NAME NOT LIKE '%Test%' AND R2.RESOURCE_NAME NOT LIKE '%romanyuta%'
AND  R2.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND  R2.RESOURCE_NAME NOT LIKE '%1000%'

group by
DT.LABEL_YYYY_MM_DD
,DT.CAL_DATE
,R2.RESOURCE_NAME
,IRF.RING_DURATION 
,IRF.TALK_DURATION
,R2.AGENT_LAST_NAME
,R2.AGENT_FIRST_NAME
,IRF.INTERACTION_ID
,IRF.HOLD_DURATION 
,IRF.AFTER_CALL_WORK_DURATION 
,IRF.TALK_COUNT
,RS.STATE_NAME
,SRSTF.TOTAL_DURATION

UNION 

select
R2.RESOURCE_NAME as RESOURCE_NAME
,R2.AGENT_LAST_NAME as AGENT_LAST_NAME
,R2.AGENT_FIRST_NAME as AGENT_FIRST_NAME
,DT.LABEL_YYYY_MM_DD as "Date"
,cast(DATEADD(hour,2,DT.CAL_DATE) AS time(0)) AS "Hours"
,'' as I_ID
,'' as N_Inb
,'' as N_Outb
,'' as N_Outb_Repl
,'' as N_Outb_New
,'' as N_obr
,'' AS N_Initiated
,CASE WHEN RS.STATE_NAME ='Busy' THEN SRSTF.TOTAL_DURATION ELSE '' END AS [Busy Duration] -- busy duration
,'' AS [RINGING DURATION]
,'' AS [TALK DURATION]
,'' AS HOLD_DURATION
,'' AS AFTER_CALL_WORK_DURATION
,'' AS TALK_COUNT
,'' as "AHT_voice"

from
INFOMART.dbo.MEDIATION_SEGMENT_FACT MSF
inner join INFOMART.dbo.INTERACTION_RESOURCE_FACT IRF on MSF.INTERACTION_ID=IRF.INTERACTION_ID
inner join INFOMART.dbo.TECHNICAL_DESCRIPTOR TD2 on IRF.TECHNICAL_DESCRIPTOR_KEY=TD2.TECHNICAL_DESCRIPTOR_KEY
inner join INFOMART.dbo.RESOURCE_ R2 on IRF.RESOURCE_KEY=R2.RESOURCE_KEY
inner join INFOMART.dbo.DATE_TIME DT on IRF.END_DATE_TIME_KEY=DT.DATE_TIME_KEY
inner JOIN INFOMART.dbo.DATE_TIME DT2 ON IRF.START_DATE_TIME_KEY = DT2.DATE_TIME_KEY
inner join INFOMART.dbo.MEDIA_TYPE M on IRF.MEDIA_TYPE_KEY=M.MEDIA_TYPE_KEY
inner join INFOMART.dbo.INTERACTION_TYPE IT on IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
inner join INFOMART.dbo.IRF_USER_DATA_KEYS UK on IRF.INTERACTION_RESOURCE_ID=UK.INTERACTION_RESOURCE_ID

INNER JOIN SM_RES_STATE_FACT SRSTF ON SRSTF.RESOURCE_KEY = R2.RESOURCE_KEY
INNER JOIN RESOURCE_STATE RS ON SRSTF.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY

WHERE 
DT.LABEL_YYYY_MM_DD = '2020-01-03'
and M.MEDIA_NAME='Email'
and R2.RESOURCE_TYPE='Agent'
AND NOT R2.RESOURCE_NAME IN ('aionov','daniel', 'aamelin')
AND R2.RESOURCE_NAME NOT LIKE '%Test%' AND R2.RESOURCE_NAME NOT LIKE '%romanyuta%'
AND  R2.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND  R2.RESOURCE_NAME NOT LIKE '%1000%'


) as T1

--WHERE T1.RESOURCE_NAME LIKE '%f.bek%' --test purpose
group BY 
T1.RESOURCE_NAME
,T1.AGENT_LAST_NAME
,T1.AGENT_FIRST_NAME
,T1."Date", T1."Hours"
order by 
T1.RESOURCE_NAME
,T1."Date", T1."Hours"
