SELECT
cast(US.G_RECEIVED_D AS date)
-- ,US.G_FROM_NAME
-- ,US.G_ORIGIN_SOURCE
-- ,US.G_FROM_ADDRESS
,DI.CUSTOMERLANG  
-- ,DI.CUSTOMERPROJECT 
-- ,case when ID.BUSINESS_RESULT='DEFAULT_BUSINESS_RESULT' then 'No business result' else ID.BUSINESS_RESULT end  
FROM INFOMART.dbo.GIDB_GM_F_USERDATA US
left join INFOMART.dbo.INTERACTION_FACT I  on US.G_FROM_ADDRESS=I.SOURCE_ADDRESS
left join INFOMART.dbo.MEDIATION_SEGMENT_FACT MSF  on MSF.INTERACTION_ID=I.INTERACTION_ID
left join INFOMART.dbo.IRF_USER_DATA_KEYS UK on MSF.IXN_RESOURCE_ID=UK.INTERACTION_RESOURCE_ID
left join INFOMART.dbo.CUST_DIM_INTERACTION DI on UK.CUST_DIM_INTERACTION=DI.ID
left join INFOMART.dbo.INTERACTION_DESCRIPTOR ID on UK.INTERACTION_DESCRIPTOR_KEY=ID.INTERACTION_DESCRIPTOR_KEY
WHERE G_SUB_TYPE='InboundNew'
--AND LEN(G_FROM_NAME)>5
AND cast(US.G_RECEIVED_D AS date)='2020-01-08'
--AND DI.CUSTOMERLANG IN ('FR','EN','it','ES','se')
GROUP BY 
US.G_RECEIVED_D
-- ,US.G_FROM_NAME
-- ,US.G_ORIGIN_SOURCE
-- ,US.G_FROM_ADDRESS
 ,DI.CUSTOMERLANG  
-- ,DI.CUSTOMERPROJECT
-- ,ID.BUSINESS_RESULT