SELECT TOP 500 DATE.LABEL_YYYY_MM_DD AS Date,
			cast(DATEADD(hour,2,DATE .CAL_DATE) AS time(0)) AS Hours,
			R.RESOURCE_NAME AS ID, (R.AGENT_FIRST_NAME+' '+ R.AGENT_LAST_NAME) as FullName,VQ.RESOURCE_NAME AS Language,


			-- Outbound section START --


count(distinct case when IRF.TALK_COUNT>0 and IT.INTERACTION_TYPE='Outbound' then IRF.INTERACTION_ID end) as [Outbound calls] -- outbound calls
,count(distinct case when IRF.TALK_COUNT=0 and IT.INTERACTION_TYPE='Outbound' then IRF.INTERACTION_ID end) as [Outbound calls not connected] -- outbound that didnt connect

		,COUNT (DISTINCT CASE WHEN TD.TECHNICAL_RESULT='Transferred' THEN IRF.INTERACTION_ID END) AS [Transferred]
		,case when (IRF.TALK_COUNT)>0 and IT.INTERACTION_TYPE='Outbound' then SUM(IRF.TALK_DURATION) ELSE '' end AS [outb Talk Time],
		case when (IRF.TALK_COUNT)>0 and IT.INTERACTION_TYPE='Outbound' then SUM(IRF.RING_DURATION) ELSE '' end AS [outb Ring Dutation],
		case when (IRF.TALK_COUNT)>0 and IT.INTERACTION_TYPE='Outbound' then SUM(IRF.HOLD_DURATION) ELSE '' end AS [outb Hold Time],
		CASE WHEN (IRF.AFTER_CALL_WORK_COUNT)>0 and (IRF.TALK_COUNT)>0 and IT.INTERACTION_TYPE='Outbound' then SUM(IRF.AFTER_CALL_WORK_DURATION) ELSE '' END AS [Outb After Call Work Time]
		



		-- Outbound section END --

		-- inbound sections START --

		,COUNT(distinct case when IRF.TALK_COUNT>0 and IT.INTERACTION_TYPE='Inbound' then IRF.INTERACTION_ID end) as [Inbound calls],
		
		case when (IRF.TALK_COUNT)>0 and IT.INTERACTION_TYPE='Inbound' then SUM(IRF.TALK_DURATION) ELSE '' end AS [Inb Talk Time],
		case when (IRF.TALK_COUNT)>0 and IT.INTERACTION_TYPE='Inbound' then SUM(IRF.RING_DURATION) ELSE '' end AS [Inb Ring Dutation],
		case when (IRF.TALK_COUNT)>0 and IT.INTERACTION_TYPE='Inbound' then SUM(IRF.HOLD_DURATION) ELSE '' end AS [Inb Hold Time],
		CASE WHEN (IRF.AFTER_CALL_WORK_COUNT)>0 and IT.INTERACTION_TYPE='Inbound' THEN SUM(IRF.AFTER_CALL_WORK_DURATION) ELSE '' END AS [AVG Inb After Call Work Time]
		


		-- inbound sections END --



				
FROM INTERACTION_RESOURCE_FACT AS IRF
		INNER JOIN INTERACTION_TYPE AS IT ON IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
		INNER JOIN TECHNICAL_DESCRIPTOR AS TD ON IRF.TECHNICAL_DESCRIPTOR_KEY=TD.TECHNICAL_DESCRIPTOR_KEY
		INNER JOIN DATE_TIME AS DATE ON IRF.START_DATE_TIME_KEY=DATE.DATE_TIME_KEY
		LEFT JOIN MEDIA_TYPE AS MT ON IRF.MEDIA_TYPE_KEY=MT.MEDIA_TYPE_KEY

		INNER JOIN RESOURCE_ R ON IRF.RESOURCE_KEY=R.RESOURCE_KEY
		INNER JOIN RESOURCE_ VQ ON IRF.LAST_VQUEUE_RESOURCE_KEY=VQ.RESOURCE_KEY

		LEFT JOIN IRF_USER_DATA_KEYS AS UDK ON IRF.INTERACTION_RESOURCE_ID=UDK.INTERACTION_RESOURCE_ID
		LEFT JOIN CUST_DIM_INTERACTION AS CDI ON UDK.CUST_DIM_INTERACTION=CDI.ID

			
WHERE IRF.TALK_COUNT>0
	AND MT.MEDIA_NAME='Voice'
	AND VQ.RESOURCE_NAME<>'VQ_Test_Phone_Inbound'
	AND VQ.RESOURCE_NAME<>'VQ_RU_Phone_Inbound'
	AND R.AGENT_FIRST_NAME IS NOT NULL
	AND R.AGENT_FIRST_NAME!='%Тест%'
	
	AND NOT R.RESOURCE_NAME IN ('aionov','daniel', 'aamelin')
	AND R.RESOURCE_NAME NOT LIKE '%Test%' AND R.RESOURCE_NAME NOT LIKE '%romanyuta%'
	AND  R.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND  R.RESOURCE_NAME NOT LIKE '%1000%'
AND R.RESOURCE_NAME LIKE 'y.vel%' AND (DATE.LABEL_YYYY_MM_DD BETWEEN '2020-02-05' AND '2020-02-06')
	
		
GROUP BY DATE.LABEL_YYYY_MM_DD, DATE.CAL_DATE, R.RESOURCE_NAME, R.AGENT_FIRST_NAME,
R.AGENT_LAST_NAME,IT.INTERACTION_TYPE,
VQ.RESOURCE_NAME,IRF.TALK_COUNT,IRF.AFTER_CALL_WORK_COUNT