DECLARE 
@Media varchar(255)='Voice'

select
DT.LABEL_YYYY_MM_DD AS "Интервал"
,cast(DATEADD(hour,2,DT.CAL_DATE) AS time(0)) AS [Hours]
,R.RESOURCE_NAME AS ID
,R.AGENT_LAST_NAME as "Фамилия"
,R.AGENT_FIRST_NAME as "Имя"
,case when VQ.RESOURCE_NAME<>'NONE' then VQ.RESOURCE_NAME
	  when VQ.RESOURCE_NAME='NONE' and IT.INTERACTION_TYPE='Outbound' then 'Outbound'
	  when VQ.RESOURCE_NAME='NONE' and IT.INTERACTION_TYPE='Internal' then 'Internal'
	  else VQ.RESOURCE_NAME
	  end
as "Скилл"

,COUNT (DISTINCT IRF.INTERACTION_ID) AS Offered,
		COUNT (DISTINCT CASE WHEN IRF.TALK_COUNT>0 THEN IRF.INTERACTION_ID END) AS Handled,
        
		COUNT (DISTINCT CASE WHEN TD.TECHNICAL_RESULT IN ('Abandoned','CustomerAbandoned') THEN IRF.INTERACTION_ID END) AS 'Total Abandoned',
		COUNT (DISTINCT CASE WHEN TD.RESULT_REASON IN ('AbandonedWhileQueued', 'AbandonedWhileRinging') THEN IRF.INTERACTION_ID END) AS 'Abandoned (Target)', -- только абандоны с очереди и с холда
		--уточнение по причинам абандонов
		COUNT (DISTINCT CASE WHEN TD.RESULT_REASON = 'AbandonedWhileQueued' THEN IRF.INTERACTION_ID END) AS 'Abandoned Queued',
		COUNT (DISTINCT CASE WHEN TD.RESULT_REASON = 'AbandonedWhileRinging' THEN IRF.INTERACTION_ID END) AS 'Abandoned Ringing',
		COUNT (DISTINCT CASE WHEN TD.RESULT_REASON = 'AbandonedFromHold' THEN IRF.INTERACTION_ID END) AS 'Abandoned Hold',
		CASE WHEN SUM(IRF.TALK_COUNT)>0 THEN ROUND(SUM(IRF.MEDIATION_DURATION)/SUM(IRF.TALK_COUNT),2) ELSE 0 END AS 'AVG Wait Time',
		COUNT (DISTINCT CASE WHEN IRF.TALK_COUNT>0 AND IRF.MEDIATION_DURATION<=20 THEN IRF.INTERACTION_ID END) AS 'Handled<=20sec',
		COUNT (DISTINCT CASE WHEN IRF.TALK_COUNT>0 AND IRF.MEDIATION_DURATION>20 AND IRF.MEDIATION_DURATION<=40 THEN IRF.INTERACTION_ID END) AS '20sec<Handled<=40sec',
		COUNT (DISTINCT CASE WHEN IRF.TALK_COUNT>0 AND IRF.MEDIATION_DURATION>40 AND IRF.MEDIATION_DURATION<=60 THEN IRF.INTERACTION_ID END) AS '40sec<Handled<=60sec',
		COUNT (DISTINCT CASE WHEN IRF.TALK_COUNT>0 AND IRF.MEDIATION_DURATION>60 AND IRF.MEDIATION_DURATION<=100 THEN IRF.INTERACTION_ID END) AS '60sec<Handled<=100sec',
		COUNT (DISTINCT CASE WHEN IRF.TALK_COUNT>0 AND IRF.MEDIATION_DURATION>100 THEN IRF.INTERACTION_ID END) AS 'Handled>100sec'

from
INFOMART.dbo.INTERACTION_RESOURCE_FACT IRF
left join INFOMART.dbo.TECHNICAL_DESCRIPTOR TD on IRF.TECHNICAL_DESCRIPTOR_KEY=TD.TECHNICAL_DESCRIPTOR_KEY
left join INFOMART.dbo.RESOURCE_ R on IRF.RESOURCE_KEY=R.RESOURCE_KEY
left join INFOMART.dbo.RESOURCE_ VQ on IRF.LAST_VQUEUE_RESOURCE_KEY=VQ.RESOURCE_KEY
left join INFOMART.dbo.DATE_TIME DT on IRF.START_DATE_TIME_KEY=DT.DATE_TIME_KEY
left join INFOMART.dbo.MEDIA_TYPE M on IRF.MEDIA_TYPE_KEY=M.MEDIA_TYPE_KEY
left join INFOMART.dbo.INTERACTION_TYPE IT on IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY



WHERE DATE.LABEL_YYYY_MM_DD >='2019-11-01'
 	AND IT.INTERACTION_TYPE='Inbound'
	AND MT.MEDIA_NAME='Voice'
	AND VQ.RESOURCE_NAME<>'NONE'
	AND VQ.RESOURCE_NAME<>'VQ_Test_Phone_Inbound'
	AND VQ.RESOURCE_NAME<>'VQ_RU_Phone_Inbound'
	AND R.AGENT_FIRST_NAME IS NOT NULL
	AND R.AGENT_FIRST_NAME!='%Тест%'
	
	AND NOT R.RESOURCE_NAME IN ('aionov','daniel', 'aamelin')
	AND R.RESOURCE_NAME NOT LIKE '%Test%' AND R.RESOURCE_NAME NOT LIKE '%romanyuta%'
	AND  R.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND  R.RESOURCE_NAME NOT LIKE '%1000%'
	
		--AND DT.LABEL_YYYY_MM_DD ='2019-11-27' AND R.RESOURCE_NAME LIKE '%b.nkoy%'
group by 
DT.LABEL_YYYY_MM_DD
,DT.CAL_DATE
,R.RESOURCE_NAME
,R.AGENT_LAST_NAME
,R.AGENT_FIRST_NAME
,IT.INTERACTION_TYPE
,VQ.RESOURCE_NAME
,case when VQ.RESOURCE_NAME<>'NONE' then VQ.RESOURCE_NAME
	  when VQ.RESOURCE_NAME='NONE' and IT.INTERACTION_TYPE='Outbound' then 'Outbound'
	  when VQ.RESOURCE_NAME='NONE' and IT.INTERACTION_TYPE='Internal' then 'Internal'
	  else VQ.RESOURCE_NAME
	  end