SELECT DATE.LABEL_YYYY_MM_DD AS Date,cast(DATEADD(hour,2,DATE.CAL_DATE) AS time(0)) AS Hours,
		VQ.RESOURCE_NAME AS Language,
		COUNT (DISTINCT CSF.MEDIA_SERVER_IXN_GUID) AS 'Offered',
		COUNT (DISTINCT  CASE WHEN CSF.MSG_FROM_CUSTOMERS_COUNT>0 THEN CSF.MEDIA_SERVER_IXN_GUID END) AS 'Chat (MSG Cust>0)',
		COUNT (DISTINCT CSF.MEDIA_SERVER_IXN_GUID)-COUNT (DISTINCT  CASE WHEN CSF.MSG_FROM_CUSTOMERS_COUNT>0 THEN CSF.MEDIA_SERVER_IXN_GUID END) AS 'Not msg client chats',
		COUNT (DISTINCT CASE WHEN CSF.HANDLE_COUNT>0 THEN CSF.MEDIA_SERVER_IXN_GUID END) AS 'Handle chat',
		COUNT	(DISTINCT CASE WHEN CSF.MSG_FROM_CUSTOMERS_COUNT>0 AND TD.TECHNICAL_RESULT IN ('Abandoned','CustomerAbandoned') THEN CSF.MEDIA_SERVER_IXN_GUID END) AS 'Missed Chat', --все неотвеченные чаты
		COUNT	(DISTINCT CASE WHEN	TD.RESULT_REASON IN ('AbandonedWhileRinging','AbandonedFromHold') THEN IRF.INTERACTION_ID END) AS 'Lost Chat',
		ROUND (SUM(CSF.UNTIL_FIRST_REPLY_DURATION)/COUNT(DISTINCT CSF.MEDIA_SERVER_IXN_GUID),2) AS 'AVG Wait Time (ASA), sec'--среднее время ожидания для всех клиентов 
FROM INTERACTION_RESOURCE_FACT AS IRF
		INNER JOIN INTERACTION_TYPE AS IT ON IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
		INNER JOIN TECHNICAL_DESCRIPTOR AS TD ON IRF.TECHNICAL_DESCRIPTOR_KEY=TD.TECHNICAL_DESCRIPTOR_KEY
		INNER JOIN DATE_TIME AS DATE ON IRF.START_DATE_TIME_KEY=DATE.DATE_TIME_KEY
		LEFT JOIN MEDIA_TYPE AS MT ON IRF.MEDIA_TYPE_KEY=MT.MEDIA_TYPE_KEY
			--присоединение внешних таблиц для получения страны из CUST_DIM_Interaction
		LEFT JOIN IRF_USER_DATA_KEYS AS UDK ON IRF.INTERACTION_RESOURCE_ID=UDK.INTERACTION_RESOURCE_ID
		LEFT JOIN CUST_DIM_INTERACTION AS CDI ON UDK.CUST_DIM_INTERACTION=CDI.ID
			--присоединяем таблицы для получения страны (очереди ресурса)
		INNER JOIN RESOURCE_ AS R ON IRF.RESOURCE_KEY=R.RESOURCE_KEY
		INNER JOIN RESOURCE_ VQ ON IRF.LAST_VQUEUE_RESOURCE_KEY=VQ.RESOURCE_KEY
		 --присоединяем таблицы для получения CHAT_SESSION_FACT
		INNER JOIN INTERACTION_FACT AS InF ON IRF.INTERACTION_ID=InF.INTERACTION_ID
		INNER JOIN CHAT_SESSION_FACT AS CSF ON InF.MEDIA_SERVER_IXN_GUID=CSF.MEDIA_SERVER_IXN_GUID
		 
		

			
WHERE DATE.LABEL_YYYY_MM_DD>='2019-10-01'
	AND IT.INTERACTION_TYPE='Inbound'
	AND MT.MEDIA_NAME='Chat'
	AND VQ.RESOURCE_NAME<>'NONE'
	AND VQ.RESOURCE_NAME<>'VQ_DEV_Chat'
	AND VQ.RESOURCE_NAME<>'VQ_RU_Chat'


			
GROUP BY DATE.LABEL_YYYY_MM_DD, VQ.RESOURCE_NAME,DATE.CAL_DATE

ORDER BY DATE.LABEL_YYYY_MM_DD, VQ.RESOURCE_NAME