SELECT DATE.LABEL_YYYY_MM_DD_HH24_MI AS Date,
		R.RESOURCE_NAME,(R.AGENT_LAST_NAME + ' ' + R.AGENT_FIRST_NAME) as Fullname,
		COUNT (DISTINCT CSF.MEDIA_SERVER_IXN_GUID) AS 'Offered',
		COUNT (DISTINCT  CASE WHEN CSF.MSG_FROM_CUSTOMERS_COUNT>0 THEN CSF.MEDIA_SERVER_IXN_GUID END) AS '# Chat (Client Wrote)',
		COUNT (DISTINCT  CASE WHEN CSF.MSG_FROM_CUSTOMERS_COUNT>0 AND CSF.MSG_FROM_AGENTS_COUNT = 0 THEN CSF.MEDIA_SERVER_IXN_GUID END) AS '# Unanswered chat', -- chat where the client wrote but didnt get an answer
		COUNT (DISTINCT  CASE WHEN CSF.MSG_FROM_CUSTOMERS_COUNT>0 AND CSF.MSG_FROM_AGENTS_COUNT> 0 THEN CSF.MEDIA_SERVER_IXN_GUID END) AS '# answered chat', -- chat where the client wrote but didnt get an answer
		COUNT (DISTINCT CSF.MEDIA_SERVER_IXN_GUID)-COUNT (DISTINCT  CASE WHEN CSF.MSG_FROM_CUSTOMERS_COUNT>0 THEN CSF.MEDIA_SERVER_IXN_GUID END) AS '# Chat (Empty)',
		COUNT (DISTINCT CASE WHEN CSF.HANDLE_COUNT>0 THEN CSF.MEDIA_SERVER_IXN_GUID END) AS 'Accepted Chat',
		COUNT	(DISTINCT CASE WHEN CSF.MSG_FROM_CUSTOMERS_COUNT>0 AND TD.TECHNICAL_RESULT IN ('Abandoned','CustomerAbandoned') THEN CSF.MEDIA_SERVER_IXN_GUID END) AS 'Missed Chat', --все неотвеченные чаты
		COUNT	(DISTINCT CASE WHEN	TD.RESULT_REASON IN ('AbandonedWhileRinging','AbandonedFromHold') THEN IRF.INTERACTION_ID END) AS 'Lost Chat',
		ROUND (SUM(CSF.UNTIL_FIRST_REPLY_DURATION)/COUNT(DISTINCT CSF.MEDIA_SERVER_IXN_GUID),2) AS 'AVG Wait Time (ASA), sec',--среднее время ожидания для всех клиентов
		SUM(CSF.UNTIL_FIRST_REPLY_DURATION) AS [First Reply Time],
		SUM(CSF.HANDLE_DURATION) AS [Handled Time (sec)]
		
FROM INTERACTION_RESOURCE_FACT AS IRF
		INNER JOIN INTERACTION_TYPE AS IT ON IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
		INNER JOIN TECHNICAL_DESCRIPTOR AS TD ON IRF.TECHNICAL_DESCRIPTOR_KEY=TD.TECHNICAL_DESCRIPTOR_KEY
		INNER JOIN DATE_TIME AS DATE ON IRF.START_DATE_TIME_KEY=DATE.DATE_TIME_KEY
		LEFT JOIN MEDIA_TYPE AS MT ON IRF.MEDIA_TYPE_KEY=MT.MEDIA_TYPE_KEY

			--присоединение внешних таблиц для получения страны из CUST_DIM_Interaction

		LEFT JOIN IRF_USER_DATA_KEYS AS UDK ON IRF.INTERACTION_RESOURCE_ID=UDK.INTERACTION_RESOURCE_ID
		LEFT JOIN CUST_DIM_INTERACTION AS CDI ON UDK.CUST_DIM_INTERACTION=CDI.ID

			--присоединяем таблицы для получения страны (ресурса)

		INNER JOIN RESOURCE_ AS R ON IRF.RESOURCE_KEY=R.RESOURCE_KEY

		 --присоединяем таблицы для получения CHAT_SESSION_FACT

		INNER JOIN INTERACTION_FACT AS InF ON IRF.INTERACTION_ID=InF.INTERACTION_ID
		INNER JOIN CHAT_SESSION_FACT AS CSF ON InF.MEDIA_SERVER_IXN_GUID=CSF.MEDIA_SERVER_IXN_GUID
		 
		

			
WHERE DATE.LABEL_YYYY_MM_DD > '2019-10'
 	AND 
	IT.INTERACTION_TYPE='Inbound'
	AND MT.MEDIA_NAME='Chat'

			
GROUP BY DATE.LABEL_YYYY_MM_DD, R.RESOURCE_NAME,R.AGENT_FIRST_NAME ,R.AGENT_LAST_NAME  , DATE.LABEL_YYYY_MM_DD_HH24_MI