select
dateadd(s,irf.START_TS,'19700101 03:00:00:000') AS STARTDATE
-- ,R.RESOURCE_NAME
,iudc.CUSTOMERSURVAYCOMMENT
-- ,cds.CUSTOMERSURVAYRESULT
,ifa.MEDIA_SERVER_IXN_GUID
,CDI.CUSTOMERLANG
,CASE WHEN cds.CUSTOMERSURVAYRESULT = 'cs_chat_survey_verygood' THEN 1 ELSE 0 END AS [verygood]
,CASE WHEN cds.CUSTOMERSURVAYRESULT = 'cs_chat_survey_good' THEN 1 ELSE 0 END AS [good]
,CASE WHEN cds.CUSTOMERSURVAYRESULT = 'cs_chat_survey_bad' THEN 1 ELSE 0 END AS [bad]

from [INFOMART].[dbo].[INTERACTION_RESOURCE_FACT] irf
left join [INFOMART].[dbo].[CUST_IRF_CUSTOMER] iudc on iudc.INTERACTION_RESOURCE_ID = irf.INTERACTION_RESOURCE_ID
left join [INFOMART].[dbo].[IRF_USER_DATA_KEYS] iudk on iudk.INTERACTION_RESOURCE_ID = irf.INTERACTION_RESOURCE_ID
left join [INFOMART].[dbo].[CUST_DIM_SURVAY] cds on cds.ID = iudk.CUST_DIM_SURVAY
left join [INFOMART].[dbo].RESOURCE_ R on r.RESOURCE_KEY = irf.RESOURCE_KEY
join [INFOMART].[dbo].INTERACTION_FACT ifa on ifa.INTERACTION_ID = irf.INTERACTION_ID
LEFT JOIN CUST_DIM_INTERACTION AS CDI ON iudk.CUST_DIM_INTERACTION=CDI.ID

where
 irf.START_DATE_TIME_KEY >= 1580428800
--AND irf.START_DATE_TIME_KEY <= 1583280000
 and cds.CUSTOMERSURVAYRESULT!='none'
 and (R.RESOURCE_NAME = 'BasicChatInbound_t.default.SurveyWorkflow' or R.RESOURCE_NAME = 'BasicChatInbound.default.Workflow1')
 AND CDI.CUSTOMERLANG <> 'DEV'
order by  irf.START_TS
