select
T1.RESOURCE_NAME RESOURCE_NAME
,T1."Fullname"
,T1."Date" AS "Date"
,count(distinct T1.I_ID) as "# Accepted"
,count(distinct case when T1.N_Outb_Repl>0 then T1.I_ID END) AS "# Replied"
,count(  distinct case when T1.N_obr>0 then T1.I_ID END) as "# Done"
,COUNT(DISTINCT CASE WHEN T1.N_Initiated > 0 THEN T1.I_ID END) AS "# Initiated"
,sum(T1.[TALK DURATION]) AS "Talking Time"

FROM

(select
R2.RESOURCE_NAME as RESOURCE_NAME
,(R2.AGENT_LAST_NAME +' '+ R2.AGENT_FIRST_NAME) AS "Fullname"
,DT.LABEL_YYYY_MM_DD_HH24_MI as "Date"
,IRF.INTERACTION_ID as I_ID
,count(distinct case when IT.INTERACTION_TYPE='Inbound' then IRF.INTERACTION_ID end) as N_Inb
,count(distinct case when IT.INTERACTION_TYPE='Outbound' then IRF.INTERACTION_ID end) as N_Outb
,count(distinct case when IT.INTERACTION_SUBTYPE='OutboundReply' and TD2.TECHNICAL_RESULT='Completed' then IRF.INTERACTION_ID end) as N_Outb_Repl
,count(distinct case when IT.INTERACTION_SUBTYPE='OutboundNew' then IRF.INTERACTION_ID end) as N_Outb_New
,count(distinct case when TD2.TECHNICAL_RESULT in ('Completed','Transferred') then IRF.INTERACTION_ID end) as N_obr
,COUNT(DISTINCT CASE WHEN IRF.HANDLE_COUNT <> 0 AND IT.INTERACTION_SUBTYPE_CODE = 'OUTBOUNDNEW' then IRF.INTERACTION_ID end) AS N_Initiated
, IRF.TALK_DURATION AS [TALK DURATION]

from
INFOMART.dbo.MEDIATION_SEGMENT_FACT MSF
inner join INFOMART.dbo.INTERACTION_RESOURCE_FACT IRF on MSF.INTERACTION_ID=IRF.INTERACTION_ID
inner join INFOMART.dbo.TECHNICAL_DESCRIPTOR TD2 on IRF.TECHNICAL_DESCRIPTOR_KEY=TD2.TECHNICAL_DESCRIPTOR_KEY
inner join INFOMART.dbo.RESOURCE_ R2 on IRF.RESOURCE_KEY=R2.RESOURCE_KEY
inner join INFOMART.dbo.DATE_TIME DT on IRF.END_DATE_TIME_KEY=DT.DATE_TIME_KEY
inner join INFOMART.dbo.MEDIA_TYPE M on IRF.MEDIA_TYPE_KEY=M.MEDIA_TYPE_KEY
inner join INFOMART.dbo.INTERACTION_TYPE IT on IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY


WHERE 
DT.LABEL_YYYY_MM > '2019-10'
and 
M.MEDIA_NAME='Email'
and R2.RESOURCE_TYPE='Agent'


group by
DT.LABEL_YYYY_MM_DD_HH24_MI
,R2.RESOURCE_NAME
,IRF.RING_DURATION 
,IRF.TALK_DURATION
,R2.AGENT_LAST_NAME
,R2.AGENT_FIRST_NAME
,IRF.INTERACTION_ID
,IRF.HOLD_DURATION 
,IRF.AFTER_CALL_WORK_DURATION 
,IRF.TALK_COUNT 

) as T1

-- WHERE T1.RESOURCE_NAME LIKE '%f.bek%' --test purpose
group BY 
T1.RESOURCE_NAME
,T1."Fullname"
,T1."Date"
order by 
T1.RESOURCE_NAME
,T1."Date"
