SELECT TOP 1000


FINALTB.MEDIA_SERVER_IXN_GUID AS [ID]
, DT.LABEL_YYYY_MM_DD_HH24_MI AS [Date]
, CIC.CUSTOMERAWSID AS [AWS ID]
, CIC.CUSTOMEREMAILADDRESS AS [Email Client]
, CIC.CUSTOMERPHONE AS [Phone]
, CIC.CONTACTID AS [CONTACT ID]

FROM 
(SELECT
IRF.INTERACTION_RESOURCE_ID,
IRF.INTERACTION_ID,
IRF.START_TS,
IFA.MEDIA_SERVER_IXN_GUID,
IRF.RESOURCE_KEY

FROM INTERACTION_RESOURCE_FACT IRF
LEFT JOIN INTERACTION_FACT IFA ON IFA.INTERACTION_ID=IRF.INTERACTION_ID

UNION

SELECT
IXN_RESOURCE_ID,
INTERACTION_ID,
START_TS,
MEDIA_SERVER_IXN_GUID,
RESOURCE_KEY

FROM MEDIATION_SEGMENT_FACT) AS FINALTB

LEFT JOIN DATE_TIME DT ON FINALTB.START_TS = DT.DATE_TIME_KEY
LEFT JOIN RESOURCE_ R on R.RESOURCE_KEY=FINALTB.RESOURCE_KEY
LEFT JOIN IRF_USER_DATA_KEYS UD on UD.INTERACTION_RESOURCE_ID=FINALTB.INTERACTION_RESOURCE_ID
LEFT JOIN CUST_DIM_INTERACTION CDI on CDI.ID=UD.CUST_DIM_INTERACTION

LEFT JOIN CUST_DIM_SURVAY CDS on CDS.ID=UD.CUST_DIM_SURVAY
LEFT JOIN CUST_DIM_FORM CDF on CDF.ID=UD.CUST_DIM_FORM
LEFT JOIN CUST_IRF_CUSTOMER CIC on CIC.INTERACTION_RESOURCE_ID=FINALTB.INTERACTION_RESOURCE_ID
LEFT JOIN INTERACTION_DESCRIPTOR IDE on IDE.INTERACTION_DESCRIPTOR_KEY=UD.INTERACTION_DESCRIPTOR_KEY

WHERE 
( CIC.CUSTOMERPHONE <> 'none' OR CIC.CUSTOMEREMAILADDRESS <> 'none') AND NOT CIC.CONTACTID IS NULL 