SELECT
"Дата"
,"Language"
,"inbound"
--,"AHT"
from
(select
DT.LABEL_YYYY_MM_DD as "Дата"
,VQ.RESOURCE_NAME AS "Language"
,count(I.INTERACTION_ID) as "inbound"
--,SUM(IRF.TALK_DURATION + IRF.HOLD_DURATION + IRF.AFTER_CALL_WORK_DURATION)/count(I.INTERACTION_ID) AS "AHT"

,count(distinct I.INTERACTION_ID) as N
from
INFOMART.dbo.INTERACTION_FACT I
left join INFOMART.dbo.DATE_TIME DT on I.END_DATE_TIME_KEY=DT.DATE_TIME_KEY
left join INFOMART.dbo.INTERACTION_RESOURCE_FACT IRF on I.INTERACTION_ID=IRF.INTERACTION_ID
left join INFOMART.dbo.IRF_USER_DATA_KEYS UK on IRF.INTERACTION_RESOURCE_ID=UK.INTERACTION_RESOURCE_ID
left join INFOMART.dbo.CUST_DIM_INTERACTION DI on UK.CUST_DIM_INTERACTION=DI.ID
left join INFOMART.dbo.MEDIA_TYPE M on I.MEDIA_TYPE_KEY=M.MEDIA_TYPE_KEY
left join INFOMART.dbo.TECHNICAL_DESCRIPTOR TD on IRF.TECHNICAL_DESCRIPTOR_KEY=TD.TECHNICAL_DESCRIPTOR_KEY
LEFT JOIN RESOURCE_ VQ ON IRF.LAST_VQUEUE_RESOURCE_KEY=VQ.RESOURCE_KEY
left join INFOMART.dbo.INTERACTION_TYPE IT on IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
where
DT.LABEL_YYYY_MM>='2020-05' and IT.INTERACTION_TYPE='Inbound'
--and DT.LABEL_YYYY_MM_DD<'2019--18'
and M.MEDIA_NAME='Email'


group by
VQ.RESOURCE_NAME
,DT.LABEL_YYYY_MM_DD
 ) T1
order BY 2