SELECT 

T1.[Email],
T1.[Agent],
T1.Date,
T1.[Channels],
MIN(T1.[Login Start Time]) AS [Login Start Time],
MAX(T1.[Login End Time]) AS [Login End Time],
T1.[Login Duration],
( T1.[Session ID]) AS [session]


FROM

(SELECT
R.RESOURCE_NAME AS [Email]
,(R.AGENT_LAST_NAME+' '+ R.AGENT_FIRST_NAME) AS [Agent]
,DT.LABEL_YYYY_MM_DD AS Date
, (SESSFACT.SM_RES_SESSION_FACT_KEY) AS [Session ID]
,DATEADD(hour, 2, DT.CAL_DATE + CAST(SRSF.START_TS-DT.DATE_TIME_KEY AS float)/CAST(86400 AS FLOAT))    AS [Login Start Time]
,DATEADD(hour, 2, DT.CAL_DATE + CAST(SRSF.END_TS-DT.DATE_TIME_KEY AS float)/CAST(86400 AS FLOAT))    AS [Login End Time]

,SESSFACT.TOTAL_DURATION AS [Login Duration]

,MT.MEDIA_NAME AS [Channels]

FROM DATE_TIME DT
INNER JOIN SM_RES_SESSION_FACT SESSFACT ON DT.DATE_TIME_KEY = SESSFACT.START_DATE_TIME_KEY
INNER JOIN SM_RES_STATE_FACT SRSF
INNER JOIN RESOURCE_STATE RS ON SRSF.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY
INNER JOIN RESOURCE_ R ON SRSF.RESOURCE_KEY=R.RESOURCE_KEY ON SESSFACT.SM_RES_SESSION_FACT_KEY = SRSF.SM_RES_SESSION_FACT_KEY
INNER JOIN MEDIA_TYPE MT ON SRSF.MEDIA_TYPE_KEY = MT.MEDIA_TYPE_KEY

WHERE DT.LABEL_YYYY_MM > '2019-10'



GROUP BY 

MT.MEDIA_NAME
,R.RESOURCE_NAME
,DT.CAL_DATE
,R.AGENT_FIRST_NAME
,R.AGENT_LAST_NAME
,DT.LABEL_YYYY_MM_DD
,SRSF.START_TS
,SESSFACT.SM_RES_SESSION_FACT_KEY
,SRSF.END_TS
,DT.DATE_TIME_KEY
,SESSFACT.TOTAL_DURATION

) AS T1

GROUP BY 

T1.[Email],
T1.[Agent],
T1.Date,
T1.[Channels],
T1.[Login Duration],
T1.[Session ID]