SELECT

DT.LABEL_YYYY_MM_DD_HH24_MI AS [Date]
,R.RESOURCE_NAME AS [Email Id]
, (R.AGENT_LAST_NAME+' '+R.AGENT_FIRST_NAME) AS [Full Name]
,CASE WHEN RSR.SOFTWARE_REASON_KEY='Break' THEN SUM(REAFACT.TOTAL_DURATION) ELSE '' END AS [Break Duration]
,CASE WHEN RSR.SOFTWARE_REASON_KEY='Training' THEN SUM(REAFACT.TOTAL_DURATION) ELSE '' END AS [Training Duration]
,CASE WHEN RSR.SOFTWARE_REASON_KEY='Statuses' THEN SUM(REAFACT.TOTAL_DURATION) ELSE '' END AS [Statuses Duration]
,CASE WHEN RSR.SOFTWARE_REASON_KEY='Meeting' THEN SUM(REAFACT.TOTAL_DURATION) ELSE '' END AS [Meeting Duration]
,CASE WHEN RSR.SOFTWARE_REASON_KEY='Lunch' THEN SUM(REAFACT.TOTAL_DURATION) ELSE '' END AS [Lunch Duration]
,CASE WHEN RSR.SOFTWARE_REASON_KEY='Mentoring' THEN SUM(REAFACT.TOTAL_DURATION) ELSE '' END AS [Mentoring Duration]


FROM

SM_RES_STATE_REASON_FACT REAFACT

INNER JOIN RESOURCE_ R ON REAFACT.RESOURCE_KEY = R.RESOURCE_KEY
INNER JOIN DATE_TIME DT ON REAFACT.START_DATE_TIME_KEY = DT.DATE_TIME_KEY
INNER JOIN RESOURCE_STATE RS ON REAFACT.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY
INNER JOIN RESOURCE_STATE_REASON RSR ON REAFACT.RESOURCE_STATE_REASON_KEY = RSR.RESOURCE_STATE_REASON_KEY

WHERE

DT.LABEL_YYYY_MM > '2019-10' AND

RSR.SOFTWARE_REASON_VALUE IS NOT NULL

GROUP BY

DT.LABEL_YYYY_MM_DD_HH24_MI
,R.RESOURCE_NAME
,R.AGENT_FIRST_NAME
,R.AGENT_LAST_NAME
,RS.STATE_NAME
,RSR.SOFTWARE_REASON_KEY