SELECT T1.ID AS AGENT_ID
		,T1."Date"
		,T1.lang
		,T1.reasons
		,T1.Email_Domain
		, COUNT(DISTINCT T1.I_ID) AS "# Accepted"
		,
COUNT(DISTINCT CASE WHEN T1.N_Outb_Repl>0 THEN T1.I_ID END) AS "Replied"
		, COUNT(DISTINCT CASE WHEN T1.N_obr>0 THEN T1.I_ID END) AS "Done"
		, COUNT(DISTINCT CASE WHEN T1.N_Outb_New > 0 THEN T1.I_ID END) AS "Initiated"
		, AVG(DISTINCT CASE WHEN T1.N_obr>0 THEN T1.AHT END) AS "AHT, sec"
FROM (
SELECT R2.RESOURCE_NAME AS ID		
		, DT.LABEL_YYYY_MM_DD AS "Date"
		,kk.lang
		,kk.INTERACTION_ID AS I_ID
		, COUNT(DISTINCT CASE WHEN IT.INTERACTION_TYPE='Inbound' THEN kk.INTERACTION_ID END) AS N_Inb
		, COUNT(DISTINCT CASE WHEN IT.INTERACTION_TYPE='Outbound' THEN kk.INTERACTION_ID END) AS N_Outb
		, COUNT(DISTINCT CASE WHEN IT.INTERACTION_SUBTYPE='OutboundReply' AND TD2.TECHNICAL_RESULT='Completed' THEN kk.INTERACTION_ID END) AS N_Outb_Repl
		, COUNT(DISTINCT CASE WHEN IT.INTERACTION_SUBTYPE='OutboundNew' THEN kk.INTERACTION_ID END) AS N_Outb_New
		, COUNT(DISTINCT CASE WHEN TD2.TECHNICAL_RESULT in ('Completed','Transferred') THEN kk.INTERACTION_ID END) AS N_obr
		, AVG(DISTINCT CASE WHEN TD2.TECHNICAL_RESULT in ('Completed','Transferred') THEN kk.TALK_DURATION END) AS AHT
		, kk.reasons AS reasons
		,kk.Email_Domain
FROM (
SELECT DISTINCT IRF.INTERACTION_RESOURCE_ID
,IRF.INTERACTION_ID
,IRF.RING_DURATION 
				,IRF.TALK_DURATION
			,IRF.TECHNICAL_DESCRIPTOR_KEY
			,IRF.RESOURCE_KEY
			,IRF.END_DATE_TIME_KEY
			,IRF.START_DATE_TIME_KEY
			,IRF.MEDIA_TYPE_KEY
			,IRF.INTERACTION_TYPE_KEY
			,CDI.CUSTOMERLANG AS lang
			,CDI.CUSTOMEREMAILDOMAIN AS Email_Domain
			,ID.BUSINESS_RESULT AS reasons
FROM INFOMART.dbo.INTERACTION_RESOURCE_FACT IRF

INNER JOIN INFOMART.dbo.MEDIATION_SEGMENT_FACT MSF ON MSF.INTERACTION_ID=IRF.INTERACTION_ID
INNER JOIN INFOMART.dbo.IRF_USER_DATA_KEYS UK ON IRF.INTERACTION_RESOURCE_ID=UK.INTERACTION_RESOURCE_ID
INNER JOIN INFOMART.dbo.CUST_DIM_INTERACTION CDI ON UK.CUST_DIM_INTERACTION=CDI.ID
LEFT JOIN INFOMART.dbo.INTERACTION_DESCRIPTOR ID on UK.INTERACTION_DESCRIPTOR_KEY=ID.INTERACTION_DESCRIPTOR_KEY
INNER JOIN INFOMART.dbo.CUST_DIM_TECH CDT ON CDT.ID = UK.CUST_DIM_TECH

WHERE CDT.INTERACTIONEXTTYPE = 'trust'
		) kk
INNER JOIN INFOMART.dbo.TECHNICAL_DESCRIPTOR TD2 ON kk.TECHNICAL_DESCRIPTOR_KEY=TD2.TECHNICAL_DESCRIPTOR_KEY
INNER JOIN INFOMART.dbo.RESOURCE_ R2 ON kk.RESOURCE_KEY=R2.RESOURCE_KEY
INNER JOIN INFOMART.dbo.DATE_TIME DT ON kk.END_DATE_TIME_KEY=DT.DATE_TIME_KEY
INNER JOIN INFOMART.dbo.DATE_TIME DT2 ON kk.START_DATE_TIME_KEY = DT2.DATE_TIME_KEY
INNER JOIN INFOMART.dbo.MEDIA_TYPE M ON kk.MEDIA_TYPE_KEY=M.MEDIA_TYPE_KEY
INNER JOIN INFOMART.dbo.INTERACTION_TYPE IT ON kk.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY

WHERE DT.CAL_DATE>'2019-09-30 23:59:59'
			--AND DT.LABEL_YYYY_MM_DD<='2020-01-22'
AND M.MEDIA_NAME='Email' AND R2.RESOURCE_TYPE='Agent' AND NOT R2.RESOURCE_NAME IN ('aionov','daniel', 'aamelin') AND R2.RESOURCE_NAME NOT LIKE '%Test%' AND R2.RESOURCE_NAME NOT LIKE '%romanyuta%' AND R2.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND R2.RESOURCE_NAME NOT LIKE '%1000%'
GROUP BY DT.LABEL_YYYY_MM_DD
		,kk.TALK_DURATION
		,R2.RESOURCE_NAME
		,kk.INTERACTION_ID
		,kk.lang
		,kk.reasons
		,kk.Email_Domain
) AS T1
GROUP BY T1.ID
		,T1."Date"
		,T1.lang