SELECT
DT.LABEL_YYYY_MM_DD_HH24_MI AS [Date]
,R.RESOURCE_NAME AS [Email]
,(R.AGENT_LAST_NAME+' '+ R.AGENT_FIRST_NAME) AS [Agent]
,MT.MEDIA_NAME AS [Channel]

,CASE WHEN RS.STATE_NAME ='Ready' THEN SRSTF.TOTAL_DURATION ELSE '' END AS [Ready Duration] 
,CASE WHEN RS.STATE_NAME ='NotReady' THEN SRSTF.TOTAL_DURATION ELSE '' END AS [Not Ready Duration]
,CASE WHEN RS.STATE_NAME ='Busy' THEN SRSTF.TOTAL_DURATION ELSE '' END AS [Busy Duration]
,CASE WHEN RS.STATE_NAME ='AfterCallWork' THEN SRSTF.TOTAL_DURATION ELSE '' END AS [AfterCallWork Duration]

, SRSTF.TOTAL_DURATION AS [Login Duration]

/*
Unknown
Busy
Ready
NotReady
AfterCallWork (voice only)

*/





FROM SM_RES_STATE_FACT SRSTF
INNER JOIN RESOURCE_ R ON SRSTF.RESOURCE_KEY = R.RESOURCE_KEY
INNER JOIN RESOURCE_STATE RS ON SRSTF.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY
INNER JOIN DATE_TIME DT ON SRSTF.START_DATE_TIME_KEY = DT.DATE_TIME_KEY
INNER JOIN MEDIA_TYPE MT ON SRSTF.MEDIA_TYPE_KEY = MT.MEDIA_TYPE_KEY

WHERE DT.LABEL_YYYY_MM > '2019-10' 
-- AND R.RESOURCE_NAME LIKE '%a.djo%'
 
GROUP BY 

DT.LABEL_YYYY_MM_DD_HH24_MI
,RS.STATE_NAME
,R.RESOURCE_NAME
,MT.MEDIA_NAME
,R.AGENT_FIRST_NAME
,R.AGENT_LAST_NAME
,SRSTF.TOTAL_DURATION