DECLARE @ID varchar(50), @date_start DATE;
SET @ID = '0003MaF41YY73TS7';
SET @date_start = '2020-02-10 00:00:00';
SELECT
DATEADD(ss, (TAB.START_TS) + 3 * 3600, '01.01.1970') as Начало_действия,
DATEADD(ss, (TAB.END_TS) + 3 * 3600, '01.01.1970') as Конец_действия,
TAB.END_TS-TAB.START_TS as Длительность_действия,
TAB.MEDIA_SERVER_IXN_GUID as ID_итерации,
R.RESOURCE_NAME as Ресурс,
TD.TECHNICAL_RESULT as Технический_результат,
TD.RESULT_REASON as Причина_результата,
MT.MEDIA_NAME as Тип_итерации,
CDI.CUSTOMERLANG as Язык,
CDI.CUSTOMEREMAILDOMAIN as Клиент_написал_на,
CDT.CUSTOMERIVRABANDONEDPOINT as Причина_сброса,
CDS.CUSTOMERSURVAYRESULT as Оценка_качества,
CIC.CUSTOMERAWSID as AWS_ID,
CIC.CUSTOMEREMAILADDRESS as Email_клиента,
CIC.CUSTOMERPHONE as Телефон_клиента,
IDE.BUSINESS_RESULT as Disposition_code
FROM (
SELECT
IRF.INTERACTION_RESOURCE_ID,
IRF.INTERACTION_ID,
IRF.START_DATE_TIME_KEY,
IRF.END_DATE_TIME_KEY,
IRF.START_TS,
IRF.END_TS,
IFA.MEDIA_SERVER_IXN_GUID,
IRF.RESOURCE_KEY,
IRF.TECHNICAL_DESCRIPTOR_KEY,
IRF.MEDIA_TYPE_KEY
FROM INTERACTION_RESOURCE_FACT IRF
LEFT JOIN INTERACTION_FACT IFA ON IFA.INTERACTION_ID=IRF.INTERACTION_ID
WHERE IFA.MEDIA_SERVER_IXN_GUID = @ID
AND
DATEADD(ss, (IFA.START_DATE_TIME_KEY) , '01.01.1970') > @date_start
UNION
SELECT
IXN_RESOURCE_ID,
INTERACTION_ID,
START_DATE_TIME_KEY,
END_DATE_TIME_KEY,
START_TS,
END_TS,
MEDIA_SERVER_IXN_GUID,
RESOURCE_KEY,
TECHNICAL_DESCRIPTOR_KEY,
MEDIA_TYPE_KEY
FROM MEDIATION_SEGMENT_FACT
WHERE MEDIA_SERVER_IXN_GUID = @ID
AND
DATEADD(ss, (START_DATE_TIME_KEY) , '01.01.1970') > @date_start
) TAB
LEFT JOIN MEDIA_TYPE MT on MT.MEDIA_TYPE_KEY=TAB.MEDIA_TYPE_KEY
LEFT JOIN TECHNICAL_DESCRIPTOR TD on TD.TECHNICAL_DESCRIPTOR_KEY=TAB.TECHNICAL_DESCRIPTOR_KEY
LEFT JOIN RESOURCE_ R on R.RESOURCE_KEY=TAB.RESOURCE_KEY
LEFT JOIN IRF_USER_DATA_KEYS UD on UD.INTERACTION_RESOURCE_ID=TAB.INTERACTION_RESOURCE_ID
LEFT JOIN CUST_DIM_INTERACTION CDI on CDI.ID=UD.CUST_DIM_INTERACTION
LEFT JOIN CUST_DIM_TECH CDT on CDT.ID=UD.CUST_DIM_TECH
LEFT JOIN CUST_DIM_SURVAY CDS on CDS.ID=UD.CUST_DIM_SURVAY
LEFT JOIN CUST_DIM_FORM CDF on CDF.ID=UD.CUST_DIM_FORM
LEFT JOIN CUST_IRF_CUSTOMER CIC on CIC.INTERACTION_RESOURCE_ID=TAB.INTERACTION_RESOURCE_ID
LEFT JOIN INTERACTION_DESCRIPTOR IDE on IDE.INTERACTION_DESCRIPTOR_KEY=UD.INTERACTION_DESCRIPTOR_KEY
ORDER BY TAB.MEDIA_SERVER_IXN_GUID, TAB.START_TS, TAB.END_TS;