SELECT
DT.LABEL_YYYY_MM_DD
,DT.LABEL_HH24
,R.RESOURCE_NAME
,R.AGENT_NAME
--, DT.CAL_DATE + CAST(SRSF.START_TS - DT.DATE_TIME_KEY AS FLOAT) / CAST (86400 AS FLOAT ) AS [Status Start Time]
--, DT.CAL_DATE + CAST(SRSF.END_TS - DT.DATE_TIME_KEY AS FLOAT) / CAST (86400 AS FLOAT ) AS [Status End Time]
,RS.STATE_TYPE AS [State Type]
,RS.STATE_NAME AS [State]
,SUM(SRSTF.TOTAL_DURATION) AS [State Duration]

FROM DATE_TIME DT
INNER JOIN SM_RES_SESSION_FACT SRSF ON DT.DATE_TIME_KEY = SRSF.START_DATE_TIME_KEY
INNER JOIN SM_RES_STATE_FACT SRSTF
INNER JOIN RESOURCE_STATE RS ON SRSTF.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY
INNER JOIN RESOURCE_ R ON SRSTF.RESOURCE_KEY = R.RESOURCE_KEY ON SRSF.SM_RES_SESSION_FACT_KEY = SRSTF.SM_RES_STATE_FACT_KEY


WHERE NOT R.RESOURCE_NAME IN ('aionov','daniel', 'aamelin','jan.m@autodoc.eu')
AND R.RESOURCE_NAME NOT LIKE '%Test%' AND R.RESOURCE_NAME NOT LIKE '%romanyuta%'
AND  R.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND  R.RESOURCE_NAME NOT LIKE '%1000%'
 
GROUP BY 

DT.LABEL_YYYY_MM_DD
,DT.LABEL_HH24
--,DT.DATE_TIME_KEY
--,SRSF.START_TS
--, SRSF.END_TS
,RS.STATE_NAME
,RS.STATE_TYPE
, R.RESOURCE_NAME
,R.AGENT_NAME 
, SRSTF.TOTAL_DURATION
--, DT.CAL_DATE

ORDER BY 1