SELECT R.RESOURCE_NAME, (R.AGENT_FIRST_NAME+' ' +R.AGENT_LAST_NAME) AS Name, R.AGENT_NAME, S.SKILL_NAME
FROM INFOMART.dbo.RESOURCE_SKILL_FACT_ RSF
JOIN RESOURCE_ R ON RSF.RESOURCE_KEY = R.RESOURCE_KEY
JOIN SKILL S ON RSF.SKILL_KEY = S.SKILL_KEY
WHERE R.RESOURCE_TYPE = 'Agent' AND R.RESOURCE_NAME LIKE '%@autodoc%' AND S.SKILL_NAME LIKE 'Location%'
GROUP BY R.RESOURCE_NAME, R.AGENT_FIRST_NAME, R.AGENT_LAST_NAME, R.AGENT_NAME, S.SKILL_NAME