SELECT

R.RESOURCE_NAME AS [Email_ID], 
(R.AGENT_FIRST_NAME+' ' +R.AGENT_LAST_NAME) AS [FullName],
CASE WHEN S.SKILL_NAME LIKE '__' THEN S.SKILL_NAME ELSE '' END AS [Country],
SUBSTRING(CASE WHEN S.SKILL_NAME LIKE '%Location_%' THEN S.SKILL_NAME ELSE '' END,10,2) AS [Locations],
CASE WHEN S.SKILL_NAME LIKE '%_agent' THEN S.SKILL_NAME ELSE '' END AS [Skills]


FROM 

RESOURCE_SKILL_FACT_ RSF
JOIN RESOURCE_ R ON RSF.RESOURCE_KEY = R.RESOURCE_KEY
JOIN SKILL S ON RSF.SKILL_KEY = S.SKILL_KEY
WHERE R.RESOURCE_TYPE = 'Agent' AND ( S.SKILL_NAME LIKE '__' OR S.SKILL_NAME LIKE '%chat_a%'
OR S.SKILL_NAME LIKE '%superv%' OR S.SKILL_NAME LIKE '%mail_a%' OR S.SKILL_NAME LIKE '%Location_%' )
AND NOT R.RESOURCE_NAME IN ('aionov','daniel', 'aamelin')
AND R.RESOURCE_NAME NOT LIKE '%Test%' AND R.RESOURCE_NAME NOT LIKE '%romanyuta%' AND  R.RESOURCE_NAME NOT LIKE '%yazykbaevr%' /* S.SKILL_NAME LIKE '__'  , two characters */
AND NOT (R.RESOURCE_NAME ='a.bah@autodoc.de' AND S.SKILL_NAME ='Location_MD')

GROUP BY R.RESOURCE_NAME, R.AGENT_FIRST_NAME, R.AGENT_LAST_NAME, S.SKILL_NAME

ORDER BY R.RESOURCE_NAME, R.AGENT_FIRST_NAME, R.AGENT_LAST_NAME