SELECT R.RESOURCE_NAME AS Email_ID, (R.AGENT_FIRST_NAME+' ' +R.AGENT_LAST_NAME) AS FullName, R.AGENT_NAME, S.SKILL_NAME AS Country
FROM INFOMART.dbo.RESOURCE_SKILL_FACT_ RSF
JOIN RESOURCE_ R ON RSF.RESOURCE_KEY = R.RESOURCE_KEY
JOIN SKILL S ON RSF.SKILL_KEY = S.SKILL_KEY
WHERE ( R.RESOURCE_TYPE = 'Agent')
AND NOT R.RESOURCE_NAME IN ('aionov','daniel', 'aamelin')
AND R.RESOURCE_NAME NOT LIKE '%Test%' AND R.RESOURCE_NAME NOT LIKE '%romanyuta%' AND  R.RESOURCE_NAME NOT LIKE '%yazykbaevr%' 
AND S.SKILL_NAME LIKE '__'  
GROUP BY R.RESOURCE_NAME, R.AGENT_FIRST_NAME, R.AGENT_LAST_NAME, R.AGENT_NAME, S.SKILL_NAME
ORDER BY R.RESOURCE_NAME, R.AGENT_FIRST_NAME, R.AGENT_LAST_NAME


