SELECT
DT.LABEL_YYYY_MM_DD AS [Date]
,DT.START_TS
-- ,DT.LABEL_HH24 AS [Hours]
,R.RESOURCE_NAME AS [Email]
,(R.AGENT_FIRST_NAME+' '+ R.AGENT_LAST_NAME) AS [Agent]
,MT.MEDIA_NAME AS [Channel]

,sum(CASE WHEN RS.STATE_NAME ='Ready' THEN SRSTF.TOTAL_DURATION ELSE '' END) AS [Ready Duration]
,sum(CASE WHEN RS.STATE_NAME ='NotReady' THEN SRSTF.TOTAL_DURATION ELSE '' END) AS [Not Ready Duration]
,sum(CASE WHEN RS.STATE_NAME ='Busy' THEN SRSTF.TOTAL_DURATION ELSE '' END) AS [Busy Duration]
,sum(CASE WHEN RS.STATE_NAME ='AfterCallWork' THEN SRSTF.TOTAL_DURATION ELSE '' END) AS [AfterCallWork Duration]


/*
Unknown
Busy
Ready
NotReady
AfterCallWork (voice only)

*/





FROM SM_RES_STATE_FACT SRSTF
INNER JOIN RESOURCE_ R ON SRSTF.RESOURCE_KEY = R.RESOURCE_KEY
INNER JOIN RESOURCE_STATE RS ON SRSTF.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY
INNER JOIN DATE_TIME DT ON SRSTF.START_DATE_TIME_KEY = DT.DATE_TIME_KEY
INNER JOIN MEDIA_TYPE MT ON SRSTF.MEDIA_TYPE_KEY = MT.MEDIA_TYPE_KEY

WHERE NOT R.RESOURCE_NAME IN ('aionov','daniel', 'aamelin','jan.m@autodoc.eu')
AND R.RESOURCE_NAME NOT LIKE '%Test%' AND R.RESOURCE_NAME NOT LIKE '%romanyuta%'
AND  R.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND  R.RESOURCE_NAME NOT LIKE '%1000%'

AND DT.LABEL_YYYY_MM_DD='2019-12-23' AND R.AGENT_FIRST_NAME LIKE '%Aguinaldo%'
 
GROUP BY 
R.RESOURCE_NAME
,DT.LABEL_YYYY_MM_DD
,DT.LABEL_TZ
-- ,DT.LABEL_HH24
-- ,RS.STATE_NAME
,MT.MEDIA_NAME
,R.AGENT_FIRST_NAME
,R.AGENT_LAST_NAME
,SRSTF.TOTAL_DURATION
-- ,SRSTF.SM_RES_SESSION_FACT_KEY

ORDER BY 1