SELECT 
DATE.LABEL_YYYY_MM AS Date
-- , cast(DATEADD(hour,2,DATE .CAL_DATE) AS time(0)) AS Hours
, CDI.CUSTOMERLANG
-- , IFA.SOURCE_ADDRESS  -- номер телефона клиента
, COUNT(IFA.MEDIA_SERVER_IXN_GUID) [Calls] --количество звонки

,CASE WHEN COUNT(IFA.SOURCE_ADDRESS) > 1 THEN count(IFA.MEDIA_SERVER_IXN_GUID) ELSE 0 END AS [#NotFCR] -- расчет появления тот же номер более 1 раз
,CASE WHEN COUNT(IFA.SOURCE_ADDRESS ) = 1 THEN count(IFA.MEDIA_SERVER_IXN_GUID) ELSE 0 END AS [#FCR] -- расчет появления тот же номер 1 раз


FROM INTERACTION_RESOURCE_FACT IRF

LEFT JOIN INTERACTION_TYPE AS IT ON IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
LEFT JOIN INTERACTION_FACT IFA ON  IRF.INTERACTION_RESOURCE_ID = IFA.INTERACTION_ID
LEFT JOIN TECHNICAL_DESCRIPTOR TD ON TD.TECHNICAL_DESCRIPTOR_KEY = IRF.TECHNICAL_DESCRIPTOR_KEY
LEFT JOIN DATE_TIME AS DATE ON IRF.START_DATE_TIME_KEY=DATE.DATE_TIME_KEY
LEFT JOIN MEDIA_TYPE AS MT ON IRF.MEDIA_TYPE_KEY=MT.MEDIA_TYPE_KEY

LEFT JOIN RESOURCE_ R ON IRF.RESOURCE_KEY=R.RESOURCE_KEY
LEFT JOIN RESOURCE_ VQ ON IRF.LAST_VQUEUE_RESOURCE_KEY=VQ.RESOURCE_KEY
LEFT JOIN INTERACTION_DESCRIPTOR ID ON ID.INTERACTION_DESCRIPTOR_KEY = IRF.INTERACTION_RESOURCE_ID

LEFT JOIN IRF_USER_DATA_KEYS AS UDK ON IRF.INTERACTION_RESOURCE_ID=UDK.INTERACTION_RESOURCE_ID
LEFT JOIN CUST_DIM_INTERACTION AS CDI ON UDK.CUST_DIM_INTERACTION=CDI.ID
LEFT JOIN INTERACTION_DESCRIPTOR IDE on IDE.INTERACTION_DESCRIPTOR_KEY=UDK.INTERACTION_DESCRIPTOR_KEY
LEFT JOIN CUST_IRF_CUSTOMER CIC on CIC.INTERACTION_RESOURCE_ID=IRF.INTERACTION_RESOURCE_ID

WHERE
MT.MEDIA_NAME='Voice'
AND IT.INTERACTION_TYPE='Inbound'
AND VQ.RESOURCE_NAME<>'VQ_Test_Phone_Inbound'
AND VQ.RESOURCE_NAME<>'VQ_RU_Phone_Inbound'
AND DATE.LABEL_YYYY_MM > '2019-10'
AND IFA.SOURCE_ADDRESS IS NOT NULL
-- AND IFA.SOURCE_ADDRESS <> ' '

GROUP BY CDI.CUSTOMERLANG, DATE.LABEL_YYYY_MM,IFA.SOURCE_ADDRESS
ORDER BY 1