SELECT cast(DATEADD(hour,2,DATE.CAL_DATE) AS time(0)) , I.MEDIA_SERVER_IXN_GUID , I.SOURCE_ADDRESS , I.TARGET_ADDRESS, (IRF.TALK_DURATION/60) AS [Duration(min)] ,(IRF.TALK_DURATION%60) AS [sec]

FROM INTERACTION_FACT I

JOIN DATE_TIME DT ON DT.DATE_TIME_KEY=I.START_DATE_TIME_KEY
JOIN INTERACTION_RESOURCE_FACT IRF ON IRF.INTERACTION_ID = I.INTERACTION_ID

WHERE DT.LABEL_YYYY_MM_DD = '2020-01-28' AND (IRF.TARGET_ADDRESS LIKE '%603201012%'  OR I.SOURCE_ADDRESS LIKE '%603201012%')