SELECT
R.RESOURCE_NAME AS [Email]
,(R.AGENT_FIRST_NAME+' '+ R.AGENT_LAST_NAME) AS [Agent]
,DT.LABEL_YYYY_MM_DD AS Date

,DATEADD(hour, 2, DT.CAL_DATE + CAST(SRSF.START_TS-DT.DATE_TIME_KEY AS float)/CAST(86400 AS FLOAT))    AS [Login Start Time]
,DATEADD(hour, 2, DT.CAL_DATE + CAST(SRSF.END_TS-DT.DATE_TIME_KEY AS float)/CAST(86400 AS FLOAT))    AS [Login End Time]

,SESSFACT.TOTAL_DURATION AS [Login Duration]
,SESSFACT.SM_RES_SESSION_FACT_KEY AS [Sessions]
,MT.MEDIA_NAME AS [Channels]

FROM DATE_TIME DT
INNER JOIN SM_RES_SESSION_FACT SESSFACT ON DT.DATE_TIME_KEY = SESSFACT.START_DATE_TIME_KEY
INNER JOIN SM_RES_STATE_FACT SRSF
INNER JOIN RESOURCE_STATE RS ON SRSF.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY
INNER JOIN RESOURCE_ R ON SRSF.RESOURCE_KEY=R.RESOURCE_KEY ON SESSFACT.SM_RES_SESSION_FACT_KEY = SRSF.SM_RES_SESSION_FACT_KEY
INNER JOIN MEDIA_TYPE MT ON SRSF.MEDIA_TYPE_KEY = MT.MEDIA_TYPE_KEY

WHERE NOT R.RESOURCE_NAME IN ('aionov','daniel', 'aamelin','jan.m@autodoc.eu')
AND R.RESOURCE_NAME NOT LIKE '%Test%' AND R.RESOURCE_NAME NOT LIKE '%romanyuta%'
AND  R.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND  R.RESOURCE_NAME NOT LIKE '%1000%'
--AND DT.LABEL_YYYY_MM_DD='2019-12-23' AND R.AGENT_FIRST_NAME LIKE '%Clark%'

GROUP BY 

MT.MEDIA_NAME
,R.RESOURCE_NAME
,DT.CAL_DATE
,R.AGENT_FIRST_NAME
,R.AGENT_LAST_NAME
,DT.LABEL_YYYY_MM_DD
,SRSF.START_TS
,SESSFACT.SM_RES_SESSION_FACT_KEY
,SRSF.END_TS
,DT.DATE_TIME_KEY
,DT.LABEL_YYYY_MM_DD_HH24
,SESSFACT.TOTAL_DURATION


