SELECT
cast(US.G_RECEIVED_D AS date) AS [date]
,US.G_FROM_ADDRESS AS [Client Email]
,DI.CUSTOMERLANG AS [Lang]
, US.CALLID AS [Interaction Id]   
,case when ID.BUSINESS_RESULT='DEFAULT_BUSINESS_RESULT' then 'No business result' else ID.BUSINESS_RESULT end AS [REASONS]

FROM GIDB_GM_F_USERDATA US

left join INTERACTION_FACT I  on US.G_FROM_ADDRESS=I.SOURCE_ADDRESS
left join MEDIATION_SEGMENT_FACT MSF  on MSF.INTERACTION_ID=I.INTERACTION_ID
left join IRF_USER_DATA_KEYS UK on MSF.IXN_RESOURCE_ID=UK.INTERACTION_RESOURCE_ID
left join CUST_DIM_INTERACTION DI on UK.CUST_DIM_INTERACTION=DI.ID
left join INTERACTION_DESCRIPTOR ID on UK.INTERACTION_DESCRIPTOR_KEY=ID.INTERACTION_DESCRIPTOR_KEY
LEFT JOIN RESOURCE_ R ON I.MEDIA_SERVER_IXN_ID = R.RESOURCE_KEY

WHERE (G_SUB_TYPE='InboundNew' OR G_SUB_TYPE='InboundCustomerReply')
AND ID.BUSINESS_RESULT IS NOT NULL
AND US.G_RECEIVED_D BETWEEN '2020-01-06' AND '2020-01-11'
GROUP BY 
US.G_RECEIVED_D
,US.G_ORIGIN_SOURCE
,US.G_FROM_ADDRESS
,DI.CUSTOMERLANG
,ID.BUSINESS_RESULT
, US.CALLID