SELECT
DT.LABEL_YYYY_MM_DD AS [Date]
,R.RESOURCE_NAME AS [Email]
,(R.AGENT_FIRST_NAME+' '+ R.AGENT_LAST_NAME) AS [Agent]
,CASE WHEN RS.STATE_NAME ='Ready' THEN SUM(SRSTF.TOTAL_DURATION) ELSE '' END AS [Ready Duration] 
,CASE WHEN RS.STATE_NAME ='NotReady' THEN SUM(SRSTF.TOTAL_DURATION) ELSE '' END AS [Not Ready Duration]
,CASE WHEN RS.STATE_NAME ='Busy' THEN SUM(SRSTF.TOTAL_DURATION) ELSE '' END AS [Busy Duration]
,CASE WHEN RS.STATE_NAME ='AfterCallWork' THEN SUM(SRSTF.TOTAL_DURATION) ELSE '' END AS [AfterCallWork Duration]
,count(distinct case when TD.TECHNICAL_RESULT in ('Completed','Transferred') then IRF.INTERACTION_ID end) as N_obr

/*
Unknown
Busy
Ready
NotReady
AfterCallWork (voice only)

*/





FROM SM_RES_STATE_FACT SRSTF
INNER JOIN RESOURCE_ R ON SRSTF.RESOURCE_KEY = R.RESOURCE_KEY
INNER JOIN RESOURCE_STATE RS ON SRSTF.RESOURCE_STATE_KEY = RS.RESOURCE_STATE_KEY
INNER JOIN DATE_TIME DT ON SRSTF.START_DATE_TIME_KEY = DT.DATE_TIME_KEY

/*something start*/

inner join INTERACTION_RESOURCE_FACT IRF on IRF.RESOURCE_KEY = R.RESOURCE_KEY
inner join INFOMART.dbo.MEDIA_TYPE M on IRF.MEDIA_TYPE_KEY=M.MEDIA_TYPE_KEY
inner join INFOMART.dbo.INTERACTION_TYPE IT on IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
inner join INFOMART.dbo.TECHNICAL_DESCRIPTOR TD on IRF.TECHNICAL_DESCRIPTOR_KEY=TD.TECHNICAL_DESCRIPTOR_KEY


/*something end*/

WHERE NOT R.RESOURCE_NAME IN ('aionov','daniel', 'aamelin','jan.m@autodoc.eu')
AND R.RESOURCE_NAME NOT LIKE '%Test%' AND R.RESOURCE_NAME NOT LIKE '%romanyuta%'
AND  R.RESOURCE_NAME NOT LIKE '%yazykbaevr%' AND  R.RESOURCE_NAME NOT LIKE '%1000%'

AND DT.LABEL_YYYY_MM_DD = '2020-01-27' 
-- AND R.RESOURCE_NAME LIKE '%a.djo%'
 
GROUP BY 

DT.LABEL_YYYY_MM_DD
,RS.STATE_NAME
,R.RESOURCE_NAME
,R.AGENT_FIRST_NAME
,R.AGENT_LAST_NAME

ORDER BY 1