DECLARE @Date varchar(32)='2020-01-06'
,@Date2 varchar(32)='2020-01-10' --требуемая дата

SELECT TOP 1000 
FINALTB.День,
FINALTB.Language,
FINALTB.Media,
FINALTB.Причина,
FINALTB.ID,
FINALTB.Email
-- FINALTB.Agent


-- count (FINALTB.Штук) AS "Кол-во взаимодействий" 
from
(
select distinct (IRF.INTERACTION_ID),
IDCOMPLEX.BUSINESS_RESULT "Причина",
-- IDCOMPLEX.RESOURCE_NAME AS "Agent",
--1 "Штук",
DT.LABEL_YYYY_MM_DD "День"
,DI.CUSTOMERLANG as "Language"
,M.MEDIA_NAME as "Media"
,IFACT.MEDIA_SERVER_IXN_GUID AS "ID"
,IFACT.SOURCE_ADDRESS AS "Email"

from (
select IDFULL.INTERACTION_ID,IDBS.BUSINESS_RESULT  from (
select distinct IRFID.INTERACTION_ID
from
INFOMART.dbo.INTERACTION_RESOURCE_FACT IRFID
left join INFOMART.dbo.DATE_TIME DTID on IRFID.START_DATE_TIME_KEY=DTID.DATE_TIME_KEY
where
DTID.LABEL_YYYY_MM_DD=@Date
) as IDFULL left JOIN (
----------------------------------------------------------------------------------------------
select IRF.INTERACTION_ID, ID.BUSINESS_RESULT 
-- , R.RESOURCE_NAME
from
INFOMART.dbo.INTERACTION_RESOURCE_FACT IRF
left join INFOMART.dbo.DATE_TIME DT on IRF.START_DATE_TIME_KEY=DT.DATE_TIME_KEY
left join INFOMART.dbo.IRF_USER_DATA_KEYS UK on IRF.INTERACTION_RESOURCE_ID=UK.INTERACTION_RESOURCE_ID
left join INFOMART.dbo.INTERACTION_DESCRIPTOR ID on UK.INTERACTION_DESCRIPTOR_KEY=ID.INTERACTION_DESCRIPTOR_KEY
LEFT JOIN RESOURCE_ R ON IRF.RESOURCE_KEY = R.RESOURCE_KEY
where
DT.LABEL_YYYY_MM_DD=@Date
and ID.BUSINESS_RESULT <> 'DEFAULT_BUSINESS_RESULT'
UNION
select MSF.INTERACTION_ID, ID.BUSINESS_RESULT
-- , R.RESOURCE_NAME
from
MEDIATION_SEGMENT_FACT MSF
left join DATE_TIME DT on MSF.START_DATE_TIME_KEY=DT.DATE_TIME_KEY
left join IRF_USER_DATA_KEYS UK on MSF.MEDIATION_SEGMENT_ID=UK.INTERACTION_RESOURCE_ID
left join INTERACTION_DESCRIPTOR ID on UK.INTERACTION_DESCRIPTOR_KEY=ID.INTERACTION_DESCRIPTOR_KEY
LEFT JOIN RESOURCE_ R ON MSF.RESOURCE_KEY = R.RESOURCE_KEY
where
MSF.END_DATE_TIME_KEY >= (select distinct DATE_TIME_MONTH_KEY from INFOMART.dbo.DATE_TIME where LABEL_YYYY_MM_DD = @Date)
and MSF.END_DATE_TIME_KEY < (select distinct DATE_TIME_NEXT_DAY_KEY from INFOMART.dbo.DATE_TIME where LABEL_YYYY_MM_DD = @Date2)
and ID.BUSINESS_RESULT <> 'DEFAULT_BUSINESS_RESULT'
----------------------------------------------------------------------------------------
) 
as IDBS on IDFULL.INTERACTION_ID = IDBS.INTERACTION_ID
) 

as IDCOMPLEX

left join INFOMART.dbo.INTERACTION_RESOURCE_FACT IRF on IDCOMPLEX.INTERACTION_ID = IRF.INTERACTION_ID
left join INFOMART.dbo.TECHNICAL_DESCRIPTOR TD on IRF.TECHNICAL_DESCRIPTOR_KEY=TD.TECHNICAL_DESCRIPTOR_KEY
left join INFOMART.dbo.DATE_TIME DT on IRF.START_DATE_TIME_KEY=DT.DATE_TIME_KEY
left join INFOMART.dbo.INTERACTION_TYPE IT on IRF.INTERACTION_TYPE_KEY=IT.INTERACTION_TYPE_KEY
left join INFOMART.dbo.MEDIA_TYPE M on IRF.MEDIA_TYPE_KEY=M.MEDIA_TYPE_KEY
left join INFOMART.dbo.IRF_USER_DATA_KEYS UK on IRF.INTERACTION_RESOURCE_ID=UK.INTERACTION_RESOURCE_ID
left join INFOMART.dbo.CUST_DIM_SURVAY DS on UK.CUST_DIM_SURVAY=DS.ID
left join INFOMART.dbo.CUST_DIM_INTERACTION DI on UK.CUST_DIM_INTERACTION=DI.ID
left join INFOMART.dbo.INTERACTION_FACT IFACT on IFACT.INTERACTION_ID = IRF.INTERACTION_ID
LEFT JOIN RESOURCE_ R ON IDCOMPLEX.RESOURCE_KEY = R.RESOURCE_KEY

where
DT.LABEL_YYYY_MM_DD=@Date
AND M.MEDIA_NAME = 'Email'
and IRF.ACTIVE_FLAG=0
and IRF.TALK_DURATION>0
and DI.CUSTOMERLANG = 'IT'
and IFACT.ACTIVE_FLAG = 0
and IFACT.END_DATE_TIME_KEY >= (select distinct DATE_TIME_DAY_KEY from INFOMART.dbo.DATE_TIME where LABEL_YYYY_MM_DD = @Date)
and IFACT.END_DATE_TIME_KEY < (select distinct DATE_TIME_NEXT_DAY_KEY from INFOMART.dbo.DATE_TIME where LABEL_YYYY_MM_DD = @Date2)
) 

as FINALTB

group BY 
FINALTB.День,
FINALTB.Language,
FINALTB.Media,
FINALTB.Причина
,FINALTB.ID
,FINALTB.Email
-- ,FINALTB.Agent


ORDER BY FINALTB.День,
FINALTB.Language,
FINALTB.Media,
FINALTB.Причина