SELECT DATE_TIME.LABEL_YYYY_MM_DD, 
		INTERACTION_DESCRIPTOR.CUSTOMER_SEGMENT, 
		INTERACTION_DESCRIPTOR.SERVICE_TYPE,
		INTERACTION_DESCRIPTOR.SERVICE_SUBTYPE,
		INTERACTION_DESCRIPTOR.BUSINESS_RESULT,
		MEDIA_TYPE.MEDIA_NAME,
		SUM(INTERACTION_RESOURCE_FACT.TALK_DURATION) AS Talk_Time,
		SUM(INTERACTION_RESOURCE_FACT.RING_DURATION) AS Ring_Time,
		SUM(INTERACTION_RESOURCE_FACT.AFTER_CALL_WORK_DURATION) AS ACW_Time,
		SUM(INTERACTION_RESOURCE_FACT.HANDLE_COUNT) AS Inreractions_Handled,
		(SUM(INTERACTION_RESOURCE_FACT.TALK_DURATION)+SUM(INTERACTION_RESOURCE_FACT.RING_DURATION)+SUM(INTERACTION_RESOURCE_FACT.DIAL_DURATION)+SUM(INTERACTION_RESOURCE_FACT.HOLD_DURATION)+SUM(INTERACTION_RESOURCE_FACT.AFTER_CALL_WORK_DURATION))/SUM(INTERACTION_RESOURCE_FACT.HANDLE_COUNT) AS AHT
FROM INTERACTION_RESOURCE_FACT
		INNER JOIN MEDIA_TYPE
			ON INTERACTION_RESOURCE_FACT.MEDIA_TYPE_KEY=MEDIA_TYPE.MEDIA_TYPE_KEY
		INNER JOIN DATE_TIME
			ON INTERACTION_RESOURCE_FACT.START_DATE_TIME_KEY=DATE_TIME.DATE_TIME_KEY
		INNER JOIN IRF_USER_DATA_KEYS
			ON INTERACTION_RESOURCE_FACT.INTERACTION_RESOURCE_ID=IRF_USER_DATA_KEYS.INTERACTION_RESOURCE_ID
		INNER JOIN INTERACTION_DESCRIPTOR
			ON IRF_USER_DATA_KEYS.INTERACTION_DESCRIPTOR_KEY=INTERACTION_DESCRIPTOR.INTERACTION_DESCRIPTOR_KEY
GROUP BY INTERACTION_DESCRIPTOR.CUSTOMER_SEGMENT, INTERACTION_DESCRIPTOR.SERVICE_TYPE, DATE_TIME.LABEL_YYYY_MM_DD, MEDIA_TYPE.MEDIA_NAME, INTERACTION_DESCRIPTOR.BUSINESS_RESULT, INTERACTION_DESCRIPTOR.SERVICE_SUBTYPE
HAVING SUM(INTERACTION_RESOURCE_FACT.HANDLE_COUNT)<>0
ORDER BY DATE_TIME.LABEL_YYYY_MM_DD, INTERACTION_DESCRIPTOR.CUSTOMER_SEGMENT, INTERACTION_DESCRIPTOR.SERVICE_TYPE, INTERACTION_DESCRIPTOR.SERVICE_SUBTYPE, INTERACTION_DESCRIPTOR.BUSINESS_RESULT, MEDIA_TYPE.MEDIA_NAME